### ISSUE TITLE
Update PyGMT version

### ISSUE THREAD

**Issue by willschlitzer** [whyjz/GMT-tutorials#18]
The current PyGMT version listed is on the first page v0.2.1; we just released v0.3.1 on March 14th [here](https://github.com/GenericMappingTools/pygmt/issues/987)!

**Comment by whyjz** [comment]
Thanks @willschlitzer for catching this! I will update this along with the other updates a couple of days later. Great job on developing the super cool PyGMT :heart:

**Comment by weiji14** [comment]
What are your current plans @whyjz? Is there anything we can help out here on this (e.g. new tutorial ideas, translations, etc). Don't want to step on each others toes too much, but there might be some opportunity to collaborate on making a PyGMT tutorial together (see https://github.com/GenericMappingTools/pygmt/issues/770).

**Comment by whyjz** [comment]
I am closing this issue by updating the PyGMT version to 0.7.0 in the tutorials. (Website is moving now, so it may need a few days to show up.)
@weiji14 and the other PyGMT developers -- I am happy to contribute to tutorials, translations, or maybe just some pretty gallery items whenever you need me. Let's keep this conversation going on PyGMT's repository! In the meantime, feel free to use or reuse any materials I wrote here in the official PyGMT doc as they are under the CC-BY 4.0 / MIT license.

**Comment by weiji14** [comment]
Cool, definitely keep in touch! I think it's nice to have it on a separate website, because it's easier to handle all the translation stuff that way.

As a quick win, you're more than welcome to add your website to the list at https://www.pygmt.org/v0.7.0/external_resources.html too. We can help to advertise it on our Twitter channel in the next release, or if you share a tweet, just ping me and I can reshare it on https://twitter.com/gmt_dev.
