### ISSUE TITLE
How to contribute to translation?

### ISSUE THREAD

**Issue by bambang** [whyjz/GMT-tutorials#8]
Hi, i would like to contribute to translation of GMT tutorials, where should I start?  I mean where to put the translation files in the directory structure? I have cloned this repo to my github account.

**Comment by whyjz** [comment]
Hi @bambang, thank you for being willing to contribute to translation! Are you planning to translate the text into English or other languages? If English, You have two options as of now:

1. Manually change the content of *.po files in SOURCE_DOCS/locale/en_US/LC_MESSAGES/. [Here](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) is a simple explanation of the format of a .po file, and after you have some edits you can directly submit them to this repo. 
2. I use Zanata and its web interface to speed up my translation work, and here is the [main page](https://translate.zanata.org/project/view/gmt-tutorials?dswid=3484) of this project. You can create an account, log in and sign up and start translating the document too. Let me know if there is anything that needs my help.

If you'd like to translate the text to languages other than English, let me know and I can create the master .po files for you. Since Zanata is discontinued in 2021, I don't think the second way is going to last long, and they also have closed new project registration. I am now trying to find another site/server that can speed up the team translation process, and that's the main reason why I waited a bit to get back to you. Let me know if you have any ideas about this as well!

**Comment by whyjz** [comment]
Hi @bambang, The community translation project of this work is now on Weblate: https://hosted.weblate.org/engage/gmt-tutorials/ where you can sign up and start translating! I am closing this issue since we will be stick to Weblate for a while. If you are still interested in this and have some time to get started, let me know how it goes!
